---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pcf-pipelines
- name: terraform-state

outputs:
- name: ip-adresses

run:
  path: pcf-pipelines/install-pcf/openstack/tasks/get-ip/task.sh
